### ISSUE TITLE
Accent

### ISSUE THREAD

**Issue by Electroso** [bitm0de/HttpsUtility#4]
There is any way to also print the special characters? Like áéíóú, because it's printed like this: '?'

**Comment by bitm0de** [comment]
Definitely possible! This would mean having an optional input on the module too since UTF-16 isn't going to work for all response message content, in the same way the default encoding doesn't work for your scenario.

`httpResponse.Encoding = Encoding.UTF8;`

This above line would need to be added before grabbing the string value from `httpResponse.ContentString` to form the `HttpsResult` here: [https://github.com/bitm0de/HttpsUtility/blob/master/HttpsUtility/Https/HttpsClientPool.cs#L79](url)

`return new HttpsResult(httpResponse.Code, httpResponse.ResponseUrl, httpResponse.ContentString);`

The other option would be to set the encoding manually and grab the string from `httpResponse.ContentBytes` instead (which is what the `httpResponse.ContentString` property does internally.

**Comment by Electroso** [comment]
First of all thank you for your answer!
I've tried what you say, and it happens exactly the same. I don't know what I'm doing wrong.
I've tried like this:
                httpResponse.Encoding = Encoding.UTF8;
                return new HttpsResult(httpResponse.Code, httpResponse.ResponseUrl, httpResponse.ContentString);
and also like this:
               return new HttpsResult(httpResponse.Code, httpResponse.ResponseUrl, httpResponse.ContentBytes);

Do I have to change anything else? Sorry I'm not good enough in Simpl#.

Thank you!

**Comment by Electroso** [comment]
Finally it works!
I've just added  httpResponse.Encoding = Encoding.UTF8;
and in the SIMPL+ module I've added #ENCODING_UTF16
Thank you so much!!
